name: Build on click

on:
  workflow_dispatch:


jobs:
  build_linux:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:

      - name: Checkout fluffychat
        uses: actions/checkout@v4
        with:
          repository: 'krille-chan/fluffychat'
          path: 'cleanchat'

      - name: Build
        run: |
          cd cleanchat
          gh workflow list
          gh workflow run releases.yml/build_linux
          