name: Build on click

on:
  workflow_dispatch:


jobs:
  build_linux:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:

      - name: Checkout fluffychat
        uses: actions/checkout@v4
        with:
          repository: 'krille-chan/fluffychat'
          path: 'cleanchat'

      - name: cd cleanchat
        run: | 
          cd cleanchat
          cat .github/workflows/versions.env >> $GITHUB_ENV
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install curl clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev libjsoncpp-dev cmake-data libsecret-1-dev libsecret-1-0 librhash0 libssl-dev -y
      
      - run: flutter pub get
      
      - run: flutter build linux --release --target-platform linux-x64
      
      - name: Create archive
        run: tar -czf fluffychat-linux-x64.tar.gz -C build/linux/x64/release/bundle/ .
      
      - name: Upload to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: fluffychat-linux-x64.tar.gz
          asset_name: fluffychat-linux-x64.tar.gz
          asset_content_type: application/gzip
        
          