name: Build Linux

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 2 * * 1"


jobs: 
  build_linux:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:

      - name: Checkout test-flows
        uses: actions/checkout@v4
        with:
          path: 'test_flows'

      - name: Checkout fluffychat
        uses: actions/checkout@v4
        with:
          repository: 'krille-chan/fluffychat'
          path: 'fluffychat'

      - name: Change to cleanchat directory
        run: |
          chmod +x test_flows/cleanchat/rename.sh
          test_flows/cleanchat/rename.sh

      - name: Get Flutter version
        run: | 
          cd fluffychat
          cat .github/workflows/versions.env >> $GITHUB_ENV
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install curl clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev libjsoncpp-dev cmake-data libsecret-1-dev libsecret-1-0 librhash0 libssl-dev webkit2gtk-4.1 -y

      - name: Build Linux
        run: |
          cd fluffychat
          flutter pub get
          flutter build linux --release --target-platform linux-x64
          tar -czf cleanchat-linux-x64.tar.gz -C build/linux/x64/release/bundle/ .
      
      - name: Upload to artifact
        uses: actions/upload-artifact@v3
        with:
          name: cleanchat-linux-x64
          path: fluffychat/cleanchat-linux-x64.tar.gz
          