name: Build on click

on:
  workflow_dispatch:


jobs:
  build_linux:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:

      - name: Checkout fluffychat
        uses: actions/checkout@v4
        with:
          repository: 'krille-chan/fluffychat'
          path: 'cleanchat'

      - name: Get Flutter version
        run: | 
          cd cleanchat
          cat .github/workflows/versions.env >> $GITHUB_ENV
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install curl clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev libjsoncpp-dev cmake-data libsecret-1-dev libsecret-1-0 librhash0 libssl-dev webkit2gtk-4.1 -y

      - name: Build Windows
        run: |
          cd cleanchat
          flutter pub get
          flutter build windows --release
          
          tar -czf cleanchat-windows-x64.tar.gz -C build/windows/ .
      
      - name: Upload to artifact
        uses: actions/upload-artifact@v3
        with:
          name: cleanchat-windows-x64
          path: cleanchat/cleanchat-windows-x64.tar.gz
        # uses: actions/upload-release-asset@v1
        # with:
        #   upload_url: ${{ github.event.release.upload_url }}
        #   asset_path: cleanchat/cleanchat-linux-x64.tar.gz
        #   asset_name: cleanchat-linux-x64.tar.gz
        #   asset_content_type: application/gzip
        
          